import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { use } from "react";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const {data: requests} = api.requests.getAll.useQuery();
  // const {data} = api.approvals.getAll.useQuery();
  const {data: approvals} = api.approvals.getAll.useQuery();

  if (!requests) return <div>Loading Requests...</div>;
  if (!approvals) return <div>Loading Approvals...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
        <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn &&
          <SignInButton mode="modal">
            <button className="btn">
              <div className="flex justify-center">Sign in</div>
            </button>
          </SignInButton>}
          {!!user.isSignedIn && <SignOutButton>
            <button className="btn">
            <div className="flex justify-center">Sign out</div>
            </button>
          </SignOutButton>}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        <div className="flex flex-col">
          <div className="justify-center border-b p-8 border-slate-400"> Requests:</div>
          {[...requests!,]?.map((request) => (
            <div className="justify-center border-b p-8 border-slate-400" key={request.id}>{request.status} - {request.content} (request id: {request.id})<br></br>Requested by: {request.requesterId}<br></br></div>
          ))}
        </div>
        <div className="flex flex-col">
          <div className="justify-center border-b p-8 border-slate-400"> Approvals:</div>
          {[...approvals!,]?.map((approval) => (
            <div className="justify-center border-b p-8 border-slate-400" key={approval.id}>{approval.id} - {approval.status}<br></br>Approved by {approval.approverId}<br></br></div>
          ))}
        </div>
        </div>
      </main>
    </>
  );
}
