import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { use } from "react";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const {data} = api.requests.getAll.useQuery();
  // const {data} = api.approvals.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="bg-blue-100">
        <div>
          {!user.isSignedIn &&
          <SignInButton mode="modal">
            <button className="btn">
              Sign in
            </button>
          </SignInButton>}
          {!!user.isSignedIn && <SignOutButton>
            <button className="btn">
              Sign Out
            </button>
          </SignOutButton>}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        <div>
          {data?.map((request) => (
            <div key={request.id}>{request.status} - {request.content}<br></br></div>
          ))}
        </div>
        {/* <div>
          {approvals?.map((approval) => (
            <div key={approval.id}>{approval.status}<br></br>{approval.status}</div>
          ))}
        </div> */}
        </div>
      </main>
    </>
  );
}
