import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { use } from "react";
import { object } from "zod";
import { api } from "~/utils/api";

const CreateRequestWizard = () => {
  const {user} = useUser();
  if (!user) return null;

  return (
    <div>
      <img src={user.imageUrl} alt="profile image"/>
    </div>
  );
}

const ApproveRequestWizard = () => {
  const {user} = useUser();
  if (!user) return null;

  return (
    <div>
      <img src={user.imageUrl} alt="profile image"/>
    </div>
  );
}

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  const {data: requests, isLoading:req_isLoading} = api.requests.getAll.useQuery();
  // const {data} = api.approvals.getAll.useQuery();
  const {data: approvals, isLoading: app_isLoading} = api.approvals.getAll.useQuery();

  if (req_isLoading) return <div>Loading...</div>;
  if (app_isLoading) return <div>Loading...</div>;
  if (!requests) return <div>Something went wrong</div>;
  if (!approvals) return <div>Something went wrong</div>;;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
        <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn &&
          <SignInButton mode="modal">
            <button className="btn">
              <div className="flex justify-center">Sign in</div>
            </button>
          </SignInButton>}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
        <div className="flex justify-center border-b border-slate-400">
          {user.isSignedIn && <CreateRequestWizard />}
        </div>
        <div className="flex flex-col">
          <div className="justify-center border-b p-8 border-slate-400"> Requests:</div>
          {[...requests,]?.map((request) => (
            <div className="justify-center border-b p-8 border-slate-400" key={request.id}>{request.status} - {request.content} (request id: {request.id})<br></br>Requested by: {request.requesterId}<br></br></div>
          ))}
        </div>
        <div className="flex flex-col">
          <div className="justify-center border-b p-8 border-slate-400"> Approvals:</div>
          {[...approvals,]?.map((approval) => (
            <div className="justify-center border-b p-8 border-slate-400" key={approval.id}>{approval.id} - {approval.status}<br></br>Approved by {approval.approverId}<br></br></div>
          ))}
        </div>
        </div>
      </main>
    </>
  );
}
